var app = getApp();
var that;
Page({
  data: {
    name:'',
    signDesc:'',
    college:'',
    time:'',
    student:'',
    price:'',
    subjectTags:'',
    skillTags:'',
    albumImages:'',
    point:'',
    talkList:'',
    isLove:false,
    showModalStatus:false,
    loveModalStatus:false,
    loveText:"您好，是关注吗？"
  },
  onShow:function(){
      that = this; 
      that.setData(
        {
          name:app.teacherDetail.name,
          signDesc:app.teacherDetail.signDesc,
          college:app.teacherDetail.college,
          time:app.teacherDetail.time,
          student:app.teacherDetail.student,
          price:app.teacherDetail.price,
          subjectTags:app.teacherDetail.subjectTags,
          skillTags:app.teacherDetail.skillTags,
          albumImages:app.teacherDetail.albumImages,
          point:app.teacherDetail.point,
          talkList:app.teacherDetail.talkList
        }
      );
      console.log(that.data.albumImages);
  },
  love:function(){
      that.setData(
        {
            loveText:"您要取消关注吗?",
            loveModalStatus:true
        });
  },
  unlove:function(){
      that.setData(
            {
                loveText:"您要关注吗?",
                loveModalStatus:true
            }
        );
  },
  modalBindaconfirm:function(){
        that.setData({
            loveModalStatus:false,
            isLove:!that.data.isLove
        });
    },
    modalBindcancel:function(){
        that.setData({
            loveModalStatus:false
        })
    },
})